### ISSUE TITLE
Out of Memory error on RTX3090

### ISSUE THREAD

**Issue by gravis778** [git-ai-code/FramePack-eichi#19]
File "n:\FramePack-Eichi\system\python\lib\site-packages\torch\nn\parameter.py", line 68, in __deepcopy__torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 18.00MiB. GPY 0 has a total capacity of 24.00 GiB of which 0 bytes is free. If the alocated memory 23.12 is allocated by pytorch and 68.18 is reserved by PyTOrch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for memory Management (https://pytorch.org.docs/stable/notes/cuda.html#environment-variables.)

Thanks for all your hard work, When I started using FramePack a week and a half ago, I was like "You know, it would be cool to have not just start frames, but also have end frames and keyframes in between. Oh, and it would be the icing on the cake if someone implemented LoRA support."

So thank you so much for this project. Much appreciated!

**Comment by git-ai-code** [comment]
Thank you for contacting us. The LoRA system we are currently using is the DynamicSwapLoRA method, which may be affecting the abundant use of VRAM. We will consider changing to a system that optimizes usage in the future. By the way, is the current GPU Memory to Preserve (GB) setting the default of 10GB? In that case, if you set it to 24GB, it may not be exhausted by using LoRA, as only the minimum 6GB will be used for processing (however, it is possible that the processing is exhausted by trying to process LoRA within that 6GB, so we will continue to investigate).

**Comment by git-ai-code** [comment]
Hello. In v1.9, with permission from Kohya Tech, we incorporated the code from [kohya-ss/FramePack-LoRAReady](https://github.com/kohya-ss/FramePack-LoRAReady) to significantly improve the performance and stability of the LoRA function, so if you are using LoRA and are running multiple concurrent chapters, please try it out.

**Comment by gravis778** [comment]
Wow, you guys are fast! I will download and get back with you shortly, doing some tests with WAN2.1 at the moment

**Comment by gravis778** [comment]
Okay, so now I am getting a memory error after it generates the first frame. I tried to let it preserve 6 gig and to let it preserve 10 gig.  I was monitoring the GPU usage in GPU-Z at preserve 10 gig, and it was using 18.6 gig up until it finished the first frame, then it filled up the VRAM and shot the error message This is the output I am getting

LoRA support is enabled
Currently enabled native sdp backends: ['flash', 'math', 'mem_efficient', 'cudnn']
Xformers is installed!
Flash Attn is installed!
Sage Attn is installed!
Free VRAM 22.759765625 GB
High-VRAM Mode: False
Downloading shards: 100%|████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  5.14it/s]
Fetching 3 files: 100%|██████████████████████████████████████████████████████████████████████████| 3/3 [00:00<?, ?it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  5.26it/s]
transformer.high_quality_fp32_output_for_inference = True
Loading output folder from settings: outputs
Starting startup default prompt loading
Successfully loaded preset file: 6 items
Loading startup default prompt: 'A character doing some simple '... (length: 45 characters)
Successfully loaded preset file: 6 items
Successfully loaded preset file: 6 items
Calculation result: Mode=1 second, Frame size=1 second (33 frames), latent_window_size=9, Total frames=30, Required sections=1
* Running on local URL:  http://127.0.0.1:8001

To create a public link, set `share=True` in `launch()`.
Section visibility update: Mode=Normal, Length=20s, Required sections=18
Calculation result: Mode=20s, Frame size=1 second (33 frames), latent_window_size=9, Total frames=600, Required sections=18
Setting frame size to 1 second mode: latent_window_size = 9

==== Starting video generation =====
◆ Generation mode: Normal mode
◆ Video length: 20 seconds
◆ Frame size: 1 second (33 frames)
◆ Number of generation sections: 18
◆ Number of sampling steps: 25
◆ Using TeaCache: True
◆ Using LoRA: True
◆ FP8最適化: False
◆ All padding: Disabled
◆ LoRA file: female_masturbation.safetensors
◆ LoRA application strength: 0.8
◆ Keyframe images: Using default settings only
=============================

Using GPU memory preservation setting: 6.0 GB
Output directory: outputs
[DEBUG] input_image shape: (480, 832, 3), type: <class 'numpy.ndarray'>
[DEBUG] end_frame shape: (2160, 3840, 3), type: <class 'numpy.ndarray'>
[DEBUG] section_settings count: 50
[DEBUG] Valid section images: 0
Setting output folder: N:\FramePack-Eichi\webui\outputs
■ Section Generation Details:
  - Planned sections: [3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0]
  - Frames per section: approximately 33 frames (latent_window_size: 9)
  - Total sections: 17
Unloaded DynamicSwap_LlamaModel as complete.
Unloaded CLIPTextModel as complete.
Unloaded SiglipVisionModel as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Unloaded DynamicSwap_HunyuanVideoTransformer3DModelPacked as complete.
Loaded CLIPTextModel to cuda:0 as complete.
Unloaded CLIPTextModel as complete.
Loaded AutoencoderKLHunyuanVideo to cuda:0 as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Loaded SiglipVisionModel to cuda:0 as complete.

■ Starting section 0 processing (Padding value: 3)
  - Current generated frames: -3 frames
  - Planned frames to generate: 33 frames
  - First section?: True
  - Last section?: False
[section_latent] section 0: using start_latent (no section_latents)
[section_latent] current_latent id: 2045047532704, min: -3.4414, max: 3.3008, mean: 0.0183
[section_prompt] Section 0 will use common prompt
latent_padding_size = 27, is_last_section = False
CUDA environment variable set: PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True (original value: )
Loading LoRA: female_masturbation.safetensors (scale: 0.8)
フォーマット: HunyuanVideo
Diffusion-pipe (?) LoRA detected
HunyuanVideo LoRA detected, converting to FramePack format
Merging LoRA weights into state dict. multiplier: 0.8
Merging LoRA weights: 100%|██████████████████████████████████████████████████████████| 520/520 [04:56<00:00,  1.75it/s]
LoRAの適用が完了しました
LoRAを直接適用しました (スケール: 0.8)
LoRA application status: True, application method: direct_application
FP8最適化は無効化されています。
Unloaded SiglipVisionModel as complete.
Setting transformer memory preservation to: 6.0 GB
Moving DynamicSwap_HunyuanVideoTransformer3DModelPacked to cuda:0 with preserved memory: 6.0 GB
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [02:29<00:00,  5.97s/it]
Offloading transformer with memory preservation: 8.0 GB
Offloading DynamicSwap_HunyuanVideoTransformer3DModelPacked from cuda:0 to preserve memory: 8.0 GB
Loaded AutoencoderKLHunyuanVideo to cuda:0 as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Decoded. Current latent shape torch.Size([1, 16, 9, 60, 104]); pixel shape torch.Size([1, 3, 33, 480, 832])
■ Section 0 processing complete
  - Current total frames: 33 frames
  - Rendering time: 1.10 seconds
  - Output file: N:\FramePack-Eichi\webui\outputs\250429_215431_432_1936_9.mp4

■ Starting section 1 processing (Padding value: 2)
  - Current generated frames: 33 frames
  - Planned frames to generate: 33 frames
  - First section?: False
  - Last section?: False
[section_latent] section 1: using start_latent (no section_latents)
[section_latent] current_latent id: 2045047532704, min: -3.4414, max: 3.3008, mean: 0.0183
[section_prompt] Section 1 will use common prompt
latent_padding_size = 18, is_last_section = False
Traceback (most recent call last):
  File "N:\FramePack-Eichi\webui\endframe_ichi.py", line 659, in worker
    transformer_obj = copy.deepcopy(transformer)
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 153, in deepcopy
  File "N:\FramePack-Eichi\system\python\lib\site-packages\torch\nn\parameter.py", line 68, in __deepcopy__
    self.data.clone(memory_format=torch.preserve_format), self.requires_grad
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 72.00 MiB. GPU 0 has a total capacity of 24.00 GiB of which 0 bytes is free. Of the allocated memory 23.12 GiB is allocated by PyTorch, and 51.46 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Unloaded DynamicSwap_LlamaModel as complete.
Unloaded CLIPTextModel as complete.
Unloaded SiglipVisionModel as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Unloaded DynamicSwap_HunyuanVideoTransformer3DModelPacked as complete.
Setting frame size to 1 second mode: latent_window_size = 9

==== Starting video generation =====
◆ Generation mode: Normal mode
◆ Video length: 20 seconds
◆ Frame size: 1 second (33 frames)
◆ Number of generation sections: 18
◆ Number of sampling steps: 25
◆ Using TeaCache: True
◆ Using LoRA: True
◆ FP8最適化: False
◆ All padding: Disabled
◆ LoRA file: female_masturbation.safetensors
◆ LoRA application strength: 0.8
◆ Keyframe images: Using default settings only
=============================

Using GPU memory preservation setting: 10.0 GB
Output directory: outputs
[DEBUG] input_image shape: (480, 832, 3), type: <class 'numpy.ndarray'>
[DEBUG] end_frame shape: (2160, 3840, 3), type: <class 'numpy.ndarray'>
[DEBUG] section_settings count: 50
[DEBUG] Valid section images: 0
Setting output folder: N:\FramePack-Eichi\webui\outputs
■ Section Generation Details:
  - Planned sections: [3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0]
  - Frames per section: approximately 33 frames (latent_window_size: 9)
  - Total sections: 17
Unloaded DynamicSwap_LlamaModel as complete.
Unloaded CLIPTextModel as complete.
Unloaded SiglipVisionModel as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Unloaded DynamicSwap_HunyuanVideoTransformer3DModelPacked as complete.
Loaded CLIPTextModel to cuda:0 as complete.
Unloaded CLIPTextModel as complete.
Loaded AutoencoderKLHunyuanVideo to cuda:0 as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Loaded SiglipVisionModel to cuda:0 as complete.

■ Starting section 0 processing (Padding value: 3)
  - Current generated frames: -3 frames
  - Planned frames to generate: 33 frames
  - First section?: True
  - Last section?: False
[section_latent] section 0: using start_latent (no section_latents)
[section_latent] current_latent id: 2044786383888, min: -3.4414, max: 3.3008, mean: 0.0183
[section_prompt] Section 0 will use common prompt
latent_padding_size = 27, is_last_section = False
Loading LoRA: female_masturbation.safetensors (scale: 0.8)
フォーマット: HunyuanVideo
Diffusion-pipe (?) LoRA detected
HunyuanVideo LoRA detected, converting to FramePack format
Merging LoRA weights into state dict. multiplier: 0.8
Merging LoRA weights: 100%|██████████████████████████████████████████████████████████| 520/520 [02:25<00:00,  3.58it/s]
LoRAの適用が完了しました
LoRAを直接適用しました (スケール: 0.8)
LoRA application status: True, application method: direct_application
FP8最適化は無効化されています。
Unloaded SiglipVisionModel as complete.
Setting transformer memory preservation to: 10.0 GB
Moving DynamicSwap_HunyuanVideoTransformer3DModelPacked to cuda:0 with preserved memory: 10.0 GB
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [02:10<00:00,  5.23s/it]
Offloading transformer with memory preservation: 8.0 GB
Offloading DynamicSwap_HunyuanVideoTransformer3DModelPacked from cuda:0 to preserve memory: 8.0 GB
Loaded AutoencoderKLHunyuanVideo to cuda:0 as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Decoded. Current latent shape torch.Size([1, 16, 9, 60, 104]); pixel shape torch.Size([1, 3, 33, 480, 832])
■ Section 0 processing complete
  - Current total frames: 33 frames
  - Rendering time: 1.10 seconds
  - Output file: N:\FramePack-Eichi\webui\outputs\250429_221624_085_4086_9.mp4

■ Starting section 1 processing (Padding value: 2)
  - Current generated frames: 33 frames
  - Planned frames to generate: 33 frames
  - First section?: False
  - Last section?: False
[section_latent] section 1: using start_latent (no section_latents)
[section_latent] current_latent id: 2044786383888, min: -3.4414, max: 3.3008, mean: 0.0183
[section_prompt] Section 1 will use common prompt
latent_padding_size = 18, is_last_section = False
Traceback (most recent call last):
  File "N:\FramePack-Eichi\webui\endframe_ichi.py", line 659, in worker
    transformer_obj = copy.deepcopy(transformer)
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 153, in deepcopy
  File "N:\FramePack-Eichi\system\python\lib\site-packages\torch\nn\parameter.py", line 68, in __deepcopy__
    self.data.clone(memory_format=torch.preserve_format), self.requires_grad
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 0 has a total capacity of 24.00 GiB of which 0 bytes is free. Of the allocated memory 23.11 GiB is allocated by PyTorch, and 60.08 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Unloaded DynamicSwap_LlamaModel as complete.
Unloaded CLIPTextModel as complete.
Unloaded SiglipVisionModel as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Unloaded DynamicSwap_HunyuanVideoTransformer3DModelPacked as complete.

**Comment by gravis778** [comment]
> Thank you for contacting us. The LoRA system we are currently using is the DynamicSwapLoRA method, which may be affecting the abundant use of VRAM. We will consider changing to a system that optimizes usage in the future. By the way, is the current GPU Memory to Preserve (GB) setting the default of 10GB? In that case, if you set it to 24GB, it may not be exhausted by using LoRA, as only the minimum 6GB will be used for processing (however, it is possible that the processing is exhausted by trying to process LoRA within that 6GB, so we will continue to investigate).

Huh, okay, let me try setting it to 24GB. I missed this comment before, let's see what happens

**Comment by gravis778** [comment]
> > Thank you for contacting us. The LoRA system we are currently using is the DynamicSwapLoRA method, which may be affecting the abundant use of VRAM. We will consider changing to a system that optimizes usage in the future. By the way, is the current GPU Memory to Preserve (GB) setting the default of 10GB? In that case, if you set it to 24GB, it may not be exhausted by using LoRA, as only the minimum 6GB will be used for processing (however, it is possible that the processing is exhausted by trying to process LoRA within that 6GB, so we will continue to investigate).
> 
> Huh, okay, let me try setting it to 24GB. I missed this comment before, let's see what happens

Okay, so this seems to work, but now its like taking 10-15 minutes between sections, and it reconverts the LoRA between sections. I seem to have quite a bit of VRAM to spare now, so let me try this with a happy medium of 16, and see what happens then. I may have to let this run overnight and get back to you guys in the morning

**Comment by gravis778** [comment]
> > > Thank you for contacting us. The LoRA system we are currently using is the DynamicSwapLoRA method, which may be affecting the abundant use of VRAM. We will consider changing to a system that optimizes usage in the future. By the way, is the current GPU Memory to Preserve (GB) setting the default of 10GB? In that case, if you set it to 24GB, it may not be exhausted by using LoRA, as only the minimum 6GB will be used for processing (however, it is possible that the processing is exhausted by trying to process LoRA within that 6GB, so we will continue to investigate).
> > 
> > 
> > Huh, okay, let me try setting it to 24GB. I missed this comment before, let's see what happens
> 
> Okay, so this seems to work, but now its like taking 10-15 minutes between sections, and it reconverts the LoRA between sections. I seem to have quite a bit of VRAM to spare now, so let me try this with a happy medium of 16, and see what happens then. I may have to let this run overnight and get back to you guys in the morning

Okay, so here is what I am noticing. Setting it to 16 gig certainly seems to be a sweet spot (could probably do 14, but that might be asking for trouble). So, set it to 16, and for the first section, I am using about 12.5 gig of vram (os + python). Between sections 1-2, vram climbs to 18.5 gig. While processing the steps in section 2, it drops to 14.5 gig vram. Between Sections 2-3 and 3-4 and 4-5, vram usage jumps to 20.5, then while processing sections 3, 4, and 5, it is using 18.5 gig vram. 

So I think I see what's going on. I am guessing that after processing section 1, it then must be loading something (data or whatever) from section 1 to generate section 2. Now for some reason, after section 2, it needs an additional 2 gig for.... something. But after that, VRAM usage seems to be consistent.

Also to note, after increasing vram usage, the amount of time needed to merge LoRAs decreased significantly (to 1-2 minutes, not sure why it varies), and the total time between sections is about 2-3 minutes, significantly faster than when I was preserving 24 gig (which makes sense)

So for me, this is now working. I am not sure what others with different memory configuration would need to do. For me the issue is solved, but I will let you guys decide if you want to close it or look into it more.

**Comment by git-ai-code** [comment]
Thank you for contacting us. We have made some changes to the way VRAM is used in separate cases #22 and #23. Please try the other one at your convenience.

**Comment by git-ai-code** [comment]
>ERROR: ASGIアプリケーションの
トレースバックの例外(最後の最後の呼び出し):
File "N:\FramePack-Eichi 1.9.1 test\system\python\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
result = await app( # type: ignore[func-returns-value]


Yes, the above error has been around for a while,
where a thumbnail doesn't appear when uploading a file.
It's difficult to deal with on this app's layer, and the file has actually been uploaded, so the only thing you can do at the moment is to ignore it or press the "X" and re-upload.

**Comment by gravis778** [comment]
> > ERROR: ASGIアプリケーションの
> > トレースバックの例外(最後の最後の呼び出し):
> > File "N:\FramePack-Eichi 1.9.1 test\system\python\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
> > result = await app( # type: ignore[func-returns-value]
> 
> Yes, the above error has been around for a while, where a thumbnail doesn't appear when uploading a file. It's difficult to deal with on this app's layer, and the file has actually been uploaded, so the only thing you can do at the moment is to ignore it or press the "X" and re-upload.

I did that, the rest of the errors appeared after that, after I chose FP8 optimized

**Comment by git-ai-code** [comment]
I see, it came out in a different pattern than usual. I'll keep an eye out to see if it happens again.

**Comment by gravis778** [comment]
Okay, 1.9.1-test2 seems to be working for me, is working just perfectly at the default preserve 10 gig, and is significantly faster!!!!

**Comment by git-ai-code** [comment]
That was very good. It was very helpful that tofu-bar only had to load LoRA the first time so I could eat it.
